[workspace]
resolver = "3"
members = ["crates/compute", "crates/viewer", "crates/deep"]

[workspace.dependencies]
rug = { version = "1.28.1", default-features = false, features = [
	"float",
	"complex",
	"std",
] }
