[package]
name = "fract"
version = "0.1.0"
edition = "2024"

[features]
default = ["compute"]
compute = ["env_logger", "pollster", "wgpu"]

[dependencies]
glazer = { path = "../blaze/crates/glazer", default-features = false, features = [
	"software",
] }
rast = { path = "../blaze/crates/rast" }
rug = { version = "1.28.1", default-features = false, features = [
	"float",
	"std",
] }

env_logger = { version = "0.11.8", optional = true }
pollster = { version = "0.4.0", optional = true }
wgpu = { version = "28.0.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "fract"
harness = false
