[package]
name = "fract"
version = "0.1.0"
edition = "2024"

[dependencies]
glazer = { path = "../blaze/crates/glazer", default-features = false }
rast = { path = "../blaze/crates/rast" }
rug = { version = "1.28.1", default-features = false, features = [
	"float",
	"std",
] }
num = "0.4.3"
env_logger = "0.11.8"
pollster = "0.4.0"
wgpu = "28.0.0"
